---

  - name: Create virtualenv
    shell: /usr/bin/virtualenv ~/pyenv creates=~/pyenv
    sudo: yes
    sudo_user: '{{user.name}}'

  - name: Install newest version of pip
    pip:  name=pip extra_args='--upgrade' virtualenv=~/pyenv
    sudo: yes
    sudo_user: '{{user.name}}'
  
  - name: Install Python packages into virtualenv.
    pip: name={{item}} virtualenv=~/pyenv
    sudo: yes
    sudo_user: '{{user.name}}'
    with_items: user.pyenv.packages

