---
  
  - name: Copy authorized keys for root
    authorized_key: 
      user: root
      key: '{{lookup("file", "files/keys/" ~ item.key_file ~ ".pub")}}'
    with_items: authorized_keys| default([])
   
  - name: Copy authorized keys for user
    authorized_key: 
      user: '{{user.name}}'
      key: '{{lookup("file", "files/keys/" ~ item.key_file ~ ".pub")}}'
    with_items: user.authorized_keys| default([])

  - name: Configure SSH client for root
    ssh_config:
      name: '{{item.name}}'
      opts: '{{item}}'
    with_items: ssh_config| default([])
  
  - name: Configure SSH client for user
    ssh_config:
      name: '{{item.name}}'
      opts: '{{item}}'
    sudo: yes
    sudo_user: '{{user.name}}'
    with_items: user.ssh_config| default([])
  
  - name: Copy public keys for root
    copy: src=files/keys/{{item.key_file}}.pub dest=~/.ssh/{{item.key_file}}.pub mode=0644
    with_items: private_keys| default([])
 
  - name: Copy private keys for root
    copy: src=files/keys/{{item.key_file}} dest=~/.ssh/{{item.key_file}} mode=0600
    with_items: private_keys| default([])
  
  - name: Copy public keys for user
    copy: src=files/keys/{{item.key_file}}.pub dest=~/.ssh/{{item.key_file}}.pub mode=0644
    sudo: yes
    sudo_user: '{{user.name}}'
    with_items: user.private_keys| default([])
 
  - name: Copy private keys for user
    copy: src=files/keys/{{item.key_file}} dest=~/.ssh/{{item.key_file}} mode=0600
    sudo: yes
    sudo_user: '{{user.name}}'
    with_items: user.private_keys| default([])

