---

  - name: Change hostname if one is provided
    hostname: name={{hostname}}
    when: hostname 
  
  # Install APT Packages
  
  - name: Add APT repository for backports
    copy: src=etc/apt/sources.list.d/jessie-backports.list dest=/etc/apt/sources.list.d/jessie-backports.list mode=0644
    when: apt.use_backports

  - name: Update APT index
    apt: update_cache=yes

  - name: Install selected APT packages
    apt: pkg={{item.1}} state=latest
    with_subelements_if_exist: 
    - apt.package_groups
    - 'packages'
    when: item.0.select| default(true)
    
