---

  - name: Create conf.d-like directory
    file: path=/etc/postgresql/{{postgres.version}}/main/conf.d state=directory owner=postgres group=postgres mode=0775
  
  - name: Determine where the data directory for the main cluster
    shell: pg_lsclusters --no-header| grep -e '^{{postgres.version}}'| cut -f 6 -d ' '
    register: pg_lsclusters_result

  - set_fact:
      data_directory: '{{pg_lsclusters_result.stdout}}'
  - debug: var=data_directory

  - name: Generate a simple configuration at postgresql.conf
    template: src=etc/postgresql/postgresql.conf dest=/etc/postgresql/{{postgres.version}}/main/postgresql.conf owner=postgres group=postgres backup=yes
    notify: [restart-postgresql]
    
  - name: Generate locally-tuned configuration at postgresql-tuned.conf
    shell: cd /etc/postgresql/{{postgres.version}}/main/ && pgtune -o postgresql-tuned.conf -i postgresql.conf
    sudo: yes
    sudo_user: postgres
    when: postgres.pgtune

  - name: Override with the tuned version of postgresql.conf
    file: path=/etc/postgresql/{{postgres.version}}/main/postgresql.conf src=postgresql-tuned.conf state=link force=yes
    when: postgres.pgtune
    notify: [restart-postgresql]

