---

  - name: Copy current key as an authorized key for user
    authorized_key: user={{user.name}} key="{{lookup('file', 'etc/ssh/authorized_keys')}}"
  
  - name: Configure client SSH for user
    copy: src=etc/ssh/ssh_config dest=~/.ssh/config mode=0640
    sudo: yes
    sudo_user: '{{user.name}}'
  
  - name: Copy RSA public keys for user
    copy: src=~/.ssh/{{item.key_file}}.pub dest=~/.ssh/id_rsa-{{item.name}}.pub mode=0644
    sudo: yes
    sudo_user: '{{user.name}}'
    with_items: private_keys
 
  - name: Copy RSA private keys for user
    copy: src=~/.ssh/{{item.key_file}} dest=~/.ssh/id_rsa-{{item.name}} mode=0600
    sudo: yes
    sudo_user: '{{user.name}}'
    with_items: private_keys

